version: '3'

volumes:
  one_saas_postgres_data: {}
  one_saas_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: one_saas_django
    container_name: one_saas_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: one_production_postgres
    container_name: one_saas_postgres
    volumes:
      - one_saas_postgres_data:/var/lib/postgresql/data
      - one_saas_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: one_saas_docs
    container_name: one_saas_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./one:/app/one:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: one_saas_mailpit
    ports:
      - '8025:8025'

  redis:
    image: redis:6
    container_name: one_saas_redis

  celeryworker:
    <<: *django
    image: one_saas_celeryworker
    container_name: one_saas_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: one_saas_celerybeat
    container_name: one_saas_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: one_saas_flower
    container_name: one_saas_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: one_saas_node
    container_name: one_saas_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'
