# Generated by Django 4.2.7 on 2023-11-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentGatewayApp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("paypal", "Paypal")], max_length=30, verbose_name="Provider")),
                ("name", models.CharField(max_length=40, verbose_name="name")),
                (
                    "client_id",
                    models.CharField(help_text="App ID, or consumer key", max_length=191, verbose_name="Client ID"),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="API secret, client secret, or consumer secret",
                        max_length=191,
                        verbose_name="secret key",
                    ),
                ),
                ("key", models.CharField(blank=True, help_text="Key", max_length=191, verbose_name="key")),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "payment gateway application",
                "verbose_name_plural": "payment gateway applications",
                "db_table": "payment_gateway_app",
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "token",
                    models.TextField(
                        help_text='"oauth_token" (OAuth1) or access token (OAuth2)', verbose_name="token"
                    ),
                ),
                (
                    "token_secret",
                    models.TextField(
                        blank=True,
                        help_text='"oauth_token_secret" (OAuth1) or refresh token (OAuth2)',
                        verbose_name="token secret",
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="expires at")),
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.paymentgatewayapp",
                        verbose_name="Payment Gateway App",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment gateway token",
                "verbose_name_plural": "payment gateway tokens",
                "db_table": "payment_gateway_token",
            },
        ),
    ]
