# Generated by Django 4.2.4 on 2023-09-03 17:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flatpages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "flatpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flatpages.flatpage",
                    ),
                ),
                ("published", models.BooleanField(default=False, verbose_name="Published")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="Description")),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="Keywords",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Page",
                "verbose_name_plural": "CMS Pages",
                "db_table": "cms_page",
            },
            bases=(meta.models.ModelMeta, "flatpages.flatpage"),
        ),
    ]
