# Generated by Django 4.2.4 on 2023-09-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Theme name")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="Description")),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="themes", verbose_name="Thumbnail")),
                (
                    "template_name",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Render Template name"),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "db_table": "cms_theme",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Template name")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="Description")),
                ("content", models.TextField(blank=True, null=True, verbose_name="Content")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="templates", verbose_name="Thumbnail"),
                ),
                ("icon", models.CharField(blank=True, max_length=255, null=True, verbose_name="Icon")),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="templates", to="ui.theme"
                    ),
                ),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
                "db_table": "cms_template",
            },
        ),
    ]
